name: Build
on:
  schedule:
    # Every 5 minutes
    #- cron: "*/5 * * * *"
    # At the end of every day
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        # checkout all branches
        fetch-depth: 0
    - name: Remove remote data branch
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git push origin :data
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.7"
    - name: Install blocklist aggregator
      run: |
        sudo python3 -m pip install blocklist_aggregator
        sudo cp blocklist.py /tmp/
    - id: today_date
      run: echo "##[set-output name=data;]$(date)"
    - name: today badge
      uses: RubbaBoy/BYOB@v1.1.0
      with:
        NAME: today
        LABEL: 'Last updated'
        STATUS: ${{ steps.today_date.outputs.data }}
        COLOR: 027CB9
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Generate, commit and push
      run: |
        git checkout --orphan data
        git rm -rf .
        sudo python3 /tmp/blocklist.py
        git add blocklist.txt
        git add hosts.txt
        git commit -m "blocklist generated"
        git push origin data
    - id: total_entries
      run: echo "##[set-output name=data;]$(wc -l blocklist.txt | awk '{ print $1 }')"
    - name: total badge
      uses: RubbaBoy/BYOB@v1.1.0
      with:
        NAME: total
        LABEL: 'Aggregated entries'
        STATUS: ${{ steps.total_entries.outputs.data }}
        COLOR: 027CB9
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}